modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"
issueTrackerURL = "https://github.com/starfish-studios/Hearth-and-Home"

[[mods]]
modId = "hearth_and_home"
version = "${version}"
displayName = "Hearth & Home"
#updateJSONURL="http://myurl.me/"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/hearth-and-home"
logoFile = "icon.png"
#credits="Thanks for this example mod goes to Java"
authors = "Starfish Studios"
description = '''
Adds a wide range of new building blocks, adding a touch of warmth and comfort to your world!
'''

[[dependencies.hearth_and_home]]
modId = "forge"
mandatory = true
versionRange = "[47.2.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hearth_and_home]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.21)"
ordering = "NONE"
side = "BOTH"
